version: "3.1"
services:
    client:
        container_name: react_client-4
        build: ./client
        ports:
            - "3333:3000"
        volumes:
            - ./client/src:/usr/src/client/src
            - ./client/public:/usr/src/client/public
        links:
            - api
        networks:
            - gotoappnetwork
    api:
        container_name: node_api-7
        build: ./server
        ports:
            - "3004:3004"
        volumes:
            - ./server:/usr/src/server
            - ./server/dist:/usr/src/server/dist
        links:
            - mongo
        networks:
            - gotoappnetwork
    mongo:
        image: mongo:4.2.1-bionic
        volumes:
            - ./mongovolume/dbmongo:/data/db
        ports:
            - "27017:27017"
        networks:
            - gotoappnetwork


    mongo-seed:
        build: .
        environment:
        - MONGODB_HOST=mongo
        - MONGODB_PORT=27017
        volumes:
        - ./db-seed:/data
        depends_on:
        - mongo
        networks:
            - gotoappnetwork        
        command: [ "mongoimport --host mongo --port 27017 --db coffee --mode upsert --type json --file /data/coffees.json --jsonArray" ]        



networks:
    gotoappnetwork:
        driver: bridge

